### ISSUE TITLE
Window focus bugs when switching between workspaces

### ISSUE THREAD

**Issue by bklaase** [WayfireWM/wayfire#1633]
**Describe the bug**
Running the git version (`c3b1edf1`) and window focus broke in the following way. Sometimes switching to a workspace with a window on it, keeps the focus on the window that was previously focused. When switching to an empty workspace if there is a previously focused window the previous window *always* will be kept in focus. Including able to receive keyboard input.
This was not the case in git version `31420a25` (month or so back ). 
 
There is a variant of this bug when actually mouseclicking alacritty windows where even switching to a new workspace with a window, will not focus the new window, until clicking (or using a switcher plugin) focusses the correct window.

**To Reproduce**
Steps to reproduce the behavior of keeping focus when switching from a 'clicked' alacritty window:
1. Enable plugin vswitch, cube, or expo
2. have alacritty, we'll call this window `a1` on `workspace 1` and have another alacritty window on `workspace 2`, we'll call it `a2`
3. with `workspace 1` focussed, click on the window. Not use whatever means to switch to `workspace 2`. the `a1` window will still be focused. Even able to receive keyboard input.

**Expected behavior**
When switching away from a  workspace the previous window becomes inactive / unfocused
when switching to a workspace the focus switches to a window on that workspace. 

**Screenshots or stacktrace**
If it is a crash, attach the backtrace (or the whole log file), Wayfire will print it in the end of the log file or stdout.
Backtrace with address sanitizer enabled (if possible):

**Wayfire version**
0.8 (`c3b1edf1`) git,

**Comment by wb9688** [comment]
Can you do a bisect to find the commit that causes the issue?

**Comment by ammen99** [comment]
I think that http://ix.io/4gPe should fix the issue, can you test and see whether anything else breaks?

**Comment by ammen99** [comment]
> Can you do a bisect to find the commit that causes the issue?

In this case, I'm fairly certain what breaks it because I changed exactly this logic recently :)

**Comment by bklaase** [comment]
Partial fix! What is fixed is the window on the new workspace NOT getting focus. What still is broken, is switching to an empty workspace. Then it still keeps a previously active window focussed from a previous workspace.

**Comment by bklaase** [comment]
trying on different system. Ibuild with `-Duse_system_wfconfig=disabled`, but still get:

    EE 25-11-22 21:51:28.293 - [src/output/plugin-loader.cpp:121] /usr/lib/wayfire/libdefault-config-backend.so: API/ABI version mismatch: Wayfire is 20221123,  plugin built with 20211126

Any idea why it is looking at that one?

**Comment by soreau** [comment]
You probably need to rebuild and restart wayfire.

**Comment by bklaase** [comment]
Thanks, but it keeps going for that. Just to check, I shuold be able to `meson`, `ninja -C build` and then run wayfire from build/src/wayfire, right? Lazy thing would be to just globally install latest git build, but I don't get why the meson param doesn't prevent it from going for global config libs

**Comment by soreau** [comment]
You might set LD_LIBRARY_PATH to build/src to see if that helps.

**Comment by bklaase** [comment]
it doesn't unfortunately. I'll just globally install latest git. Thanks for thinking along, though

**Comment by bklaase** [comment]
alright, got it running again. Unfortunately the second patch did not resolve the issue of keeping focus when switching to an empty workspace

**Comment by soreau** [comment]
Can you explain the remaining issue in detail? I tested the patch and when I switch from a focused text-input window to an empty workspace and type some characters, they no longer go to the window on the other workspace (whereas without the patch, they did).

**Comment by bklaase** [comment]
That is indeed the case. I missed that part because I focused on something else: the panel (waybar) showing the previous window as active. The registering input part seems indeed resolved.

so what's still "new" from that previous commit, is the wm "reporting" the window as active

**Comment by soreau** [comment]
I see, this also happens with wf-panel. Another thing I notice is from an empty workspace, clicking on a wf-panel window just minimizes and restores, it doesn't take you to the workspace of the window instead, like I'd expect.

**Comment by bklaase** [comment]
Hmm, I've been looking through the commits but I need more time to grasp how wayfire's parts fit together.

**Comment by ammen99** [comment]
Are you sure the last patch I posted does not fix the issue for you? I cannot reproduce locally.

**Comment by bklaase** [comment]
> Are you sure the last patch I posted does not fix the issue for you? I cannot reproduce locally.

yes, i t didn't resolve the switching to empty spaces issue. 
The PR now contains the promissing lines
 ``` cpp
else if (new_focus.node == nullptr)
    {
        update_active_view(nullptr);
    }
```

 so will try and confirm today!

**Comment by bklaase** [comment]
Sorry, after a long day I just tried it, and there is still a quirck  left.
what is fixed:
- switching to empty desktop correctly unfocusses previous 
- switching to another occupied desktop after mousefocussing focusses the new desktop's window

so everything I initially reported on.
however I found a new variant:

open two alacrittty terminals; one on desktop d1 (we call this window w1), one on desktop d2 (we'll call w2).
switch from d1 to d2; and see that all is well. w2 is now focussed.

now click window on d1
switch to d2; correctly w2 is active.
now click still active w2 -> somehow focus reverts to w1 !!!
click w2 again and it is correctly focussed, and subsequent clicks won't repeat the pattern.

however, this bug was introduced before `31420a25`, since in this older version I can reproduce this too. So perhaps it's better to accept this issue as closed an open a new one?

**Comment by ammen99** [comment]
@bklaase If this issue was present before, then indeed we'd better discuss it in a new issue. Your new issue however sounds very similar to #1636.

I'm wondering though, are the applications you are using Xwayland or Wayland native?

**Comment by bklaase** [comment]
both native clients, no Xwayland. I'm fairly conviced #1636 is the behavior I described in my opening comment. And should be resolved by this PR.  Although that is counter indicated by your bugfix branch not resolving it for him .. 
I'll experiment tomorrow with both multiple mons and desktops.
Thanks so far!

**Comment by bklaase** [comment]
resolved by #1640

**Comment by bklaase** [comment]
Resolved by #1640
