### ISSUE TITLE
Qt windows with CDS decoration shrink at every reload

### ISSUE THREAD

**Issue by stefonarch** [WayfireWM/wayfire#1723]
**Describe the bug**

When using `preferred_decoration_mode = client` the height and width will be detracted from the last size, so any Qt window like featherpad or LXimage-qt which uses the default Qt decoration will be smaller at next opening. Most annoying is this with the lxqt-filedialog which fastly gets  unusable and has to be resized.

This behavior  can only be seen in wayfire, as kwin, labwc and sway never  use the default Qt decoration (which is also very basic and cannot be customized).

**To Reproduce**
1. Open Qt application with server side deco
2. close it
3. repeat it several times

With lxqt-filedialog it can be seen in it's settings:
```
[Sizes]
WindowSize=@Size(1027 401)

# one reload:

WindowSize=@Size(1021 368) 
```

**Expected behavior**
Window sizes should be remembered.

**Screenshots **

![screen_area_ven_08:53:43_](https://user-images.githubusercontent.com/10681413/219584841-5e98a107-f1d4-4e49-b233-a1b4ad70864e.png)

LXimage-qt opened 4 times:

![screen_area_ven_09:01:24_](https://user-images.githubusercontent.com/10681413/219586339-1f423ba9-5e1b-4433-84c9-c7f49a0169a2.png)

PS. I couldn't test firedecor:  https://github.com/AhoyISki/Firedecor/issues/26

**Wayfire version**
git

**Comment by marcusbritanicus** [comment]
Well, as far as I know and understand, kwin, labwc and sway don't use CSD. All of them use server side decorations. In Wayfire, when we use `preferred_decoration_mode = server`, I think this problem isn't there. 

Regarding this particular problem, I believe when you do an interactive resize (dragging and resizing by mouse), Qt is supposed to calculate the decoration size and store the actual content size. And when showing the same dialog, Qt is expected to calculate the extra space it needs to draw borders and report the size with borders to Wayfire. I believe Qt (or LXQt) makes a few mistakes in calculating the actual window size.

**Comment by stefonarch** [comment]
Sure, it is probably a Qt bug (which probably doesn't expect anyone using its default CSD ) and with SSD it's not seen. In LXQt you  don't see it  too as it's the WM's job which isn't a part of LXQt.

**Comment by stefonarch** [comment]
I'm running in a strange problem: changed to `preferred_decoration_mode = server` and in the first moment all was ok, changed the color and from then until now _most_ Qt windows including filedialog have no deco at all, except `pcmanfm-qt`. At least the filedialog issue is gone in that way, but I wonder why this can happen.

**Comment by stefonarch** [comment]
Ok, the issue with SSD missing decorations is gone using master instead of alpha-ipc branch.

**Comment by ammen99** [comment]
Still happening?

**Comment by stefonarch** [comment]
Can't tell as I don't use master if using wayfire (waiting for lxqt-desktop-shell plugin and some others).

**Comment by xiaohuirong** [comment]
I also encounter this issue when using Wayfire built from the latest commit ea07520 of the master branch. I have tested many Qt applications, and I've found that those Qt applications that remember window sizes also experience this problem. Every time I open a Qt application, the height value in the configuration file ~/.config/xxxrc decreases.

**Comment by stefonarch** [comment]
I was using the decoration plugin, as the Qt decoration isn't that nice.

**Comment by xiaohuirong** [comment]
This is a workaround, but I can't make the decoration color consistent with both GTK and Qt applications. Should We report a bug to Qt?

**Comment by xiaohuirong** [comment]
I tried using wf-info to find the cause. In my case, the decoration height of Qt is 33. When I open Qt software, the total window height (including decoration) matches the height in the configuration file. However, when I close the Qt software, Qt stores a height that subtracts the decoration height. Therefore, each time I restart the Qt software, the height will be reduced by 33.

**Comment by stefonarch** [comment]
Done, same issue, opening and closing LXQt's filedialog 10 times was enough.

**Comment by marcusbritanicus** [comment]
> This is a workaround, but I can't make the decoration color consistent with both GTK and Qt applications. Should We report a bug to Qt?

@xiaohuirong  There is no bug. How is Qt expected to know how GTK draws it's decoration or what color it uses? Furthermore, GTK may have UI elements in  its titlebar if it's using headerbar. So Qt simply draw either light or dark titlebars based on the widget theme. This is a plugin - `bradient` that is loaded when Qt is run in wayland. If you're very adventurous, you can try to modify the QtWayland sources of this plugin and recompile.

PS: @stefonarch @xiaohuirong  If you're unhappy with Wayfire's default, you have alternatives - [windecor](https://gitlab.com/wayfireplugins/windecor) and [firedecor](https://github.com/AhoyISki/Firedecor).

**Comment by marcusbritanicus** [comment]
> I tried using wf-info to find the cause. In my case, the decoration height of Qt is 33. When I open Qt software, the total window height (including decoration) matches the height in the configuration file. However, when I close the Qt software, Qt stores a height that subtracts the decoration height. Therefore, each time I restart the Qt software, the height will be reduced by 33.

Yes. This is pretty much what is happening. The margins used by Qt's `bradient` plugin are `(3, 30, 3, 3)` which means you'll lose 33px vertically, and 6 px horizontally on every open-close cycle. Unless proven otherwise, this is still a problem with Qt, and not wayfire or any other compositor.

**Comment by ammen99** [comment]
I suppose the question is this: does the bug happen with the decoration plugin disabled, but with `preferred_decoration_mode=client`? If yes, I very strongly suspect a bug in Qt that Wayfire cannot fix.

**Comment by stefonarch** [comment]
> PS: @stefonarch @xiaohuirong If you're unhappy with Wayfire's default, you have alternatives - [windecor](https://gitlab.com/wayfireplugins/windecor) and [firedecor](https://github.com/AhoyISki/Firedecor).

In fact, it's unusable with CSD.

**Comment by marcusbritanicus** [comment]
> I suppose the question is this: does the bug happen with the decoration plugin disabled, but with `preferred_decoration_mode=client`? If yes, I very strongly suspect a bug in Qt that Wayfire cannot fix.

@ammen99 I can confirm that the bug happens with decoration plugin disabled and the mode set to client.

**Comment by ammen99** [comment]
Ok, thanks for testing @marcusbritanicus. Then it is rather clear this is a bug in Qt. Please report to them.

**Comment by xiaohuirong** [comment]
> > I tried using wf-info to find the cause. In my case, the decoration height of Qt is 33. When I open Qt software, the total window height (including decoration) matches the height in the configuration file. However, when I close the Qt software, Qt stores a height that subtracts the decoration height. Therefore, each time I restart the Qt software, the height will be reduced by 33.
> 
> Yes. This is pretty much what is happening. The margins used by Qt's `bradient` plugin are `(3, 30, 3, 3)` which means you'll lose 33px vertically, and 6 px horizontally on every open-close cycle. Unless proven otherwise, this is still a problem with Qt, and not wayfire or any other compositor.
> 
> @xiaohuirong It would be worth reporting this bug to Qt.

Thank you for explaining the reason to me. I will report a bug to QT.

**Comment by xiaohuirong** [comment]
I have reported a bug to Qt. https://bugreports.qt.io/browse/QTBUG-116874
